backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
# This line should *not* be indented
media_folder: "galeria/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - label: "Secciones"
    name: "Secciones"
    files:
      - label: "pagina sobre nosotros"
        name: "about"
        file: "/content/about.json"
        fields:
          - { label: titulo sobre nosotros, name: title, widget: string }
          - { label: 1er parrafo, name: intro, widget: markdown }
          - label: Mision
            name: mision
            widget: list
            fields:
              - { label: Titulo mision, name: title, widget: string }
              - { label: Parrafo, name: paragraph, widget: markdown }
              - { label: Imagen, name: photo, widget: image }
          - label: Vision
            name: vision
            widget: list
            fields:
              - { label: titulo vision, name: title, widget: string }
              - { label: parrafo, name: paragraph, widget: markdown }
              - { label: Imagen, name: photo, widget: image }
      - label: "Pagina contacto"
        name: "contacto"
        file: "/content/contacto.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: parrafo, name: paragraph, widget: markdown }
      - label: "Pie de pagina"
        name: "footer"
        file: "/content/footer.json"
        fields:
          - { label: Nombre logo, name: title, widget: string }
          - { label: Logo imagen, name: image, widget: image }
          - { label: Cita, name: cita, widget: string }
      - label: "Direcciones y redes"
        name: "direcciones"
        file: "/content/direcciones.json"
        fields:
          - { label: Direccion completa, name: direccion, widget: string }
          - { label: Correo, name: email, widget: string }
          - { label: Telefono, name: phone, widget: string }
          - { label: Horarios y dias, name: days, widget: string }
          - { label: Url instagram, name: ig, widget: string }
          - { label: Url facebook, name: face, widget: string }
