backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
# This line should *not* be indented
media_folder: "galeria/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - label: "Secciones"
    name: "Secciones"
    files:
      - label: "pagina sobre nosotros"
        name: "about"
        file: "/content/about.json"
        fields:
          - {label: titulo sobre nosotros, name: title, widget: string}
          - {label: 1er parrafo, name: intro, widget: markdown}
          - label: Mision
            name: mision
            widget: list
            fields:
              - {label: Titulo mision, name: title, widget: string}
              - {label: Parrafo, name: paragraph, widget: markdown}
              - {label: Imagen, name: photo, widget: image}
          - label: Vision
            name: vision
            widget: list
            fields:
              - {label: titulo vision, name: title, widget: string}
              - {label: parrafo, name: paragraph, widget: markdown}
              - {label: Imagen, name: photo, widget: image}    
      - label: "Locations Page"
        name: "locations"
        file: "/content/locations.json"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Locations
            name: locations
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Address, name: address, widget: string}